---
Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/deck-api.rb
    - lib/nextcloud-deck-api.rb
    - spec/nextcloud-deck-api_spec.rb

Style/WordArray:
  Enabled: false
